### PR TITLE
test add documentation and pull request stuff

### PR DESCRIPTION
**Pull request by katherineding**

### CODE REVIEW

**Comment by edwnh** [comment]
Could you show me the output of this on windows?

def main(argv)
    print(argv)

**Comment by edwnh** [comment]
I guess you're trying to implement wildcard expansion (which isn't done by the windows shell)? https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths

info.py and summary.py are intended to be used with single files so I don't think it is necessary to do this.

**Comment by katherineding** [comment]
Yes, I was trying to to wildcard expansion. I use summary.py with wildcard expansions to check the status of .h5 files that are being worked on. In conjunction with grep info.py is also useful for checking parameter settings quickly. My thinking was that since the two scripts run on linux with wildcard expansion automatically, the windows behavior should be the same.

**Comment by edwnh** [comment]
Apparently powershell on windows doesn't do wildcard expansions either... this is annoying but I guess necessary.

1. The variable nbins is unnecessary.
2. Instead of raising an error, just printing the message is better here because for example if I do
python summary.py abc.h5 typo.h5 def.h5
and typo.h5 is misspelled, if an error is raised then the data for def.h5 is not printed.
2. Could you also modify print_n.py and push.py? (Note for print_n.y, the variable should not be called "files" because the info() function takes a directory name with a trailing slash as an argument)

**Comment by edwnh** [comment]
by the way there's a one-line way to do this (but it's a bit hard to understand):

files = [path for arg in argv[1:] for path in glob(arg)]
for f in files:
...

**Comment by katherineding** [comment]
print_n does not need changing because it relies on util.load, which already has wildcard expansion

**Comment by katherineding** [comment]
changes have been made!

**Comment by edwnh** [comment]
print_n does because very often it is used like this:

python print_n.py beta*/n0.9/

which (in unix systems) expands to e.g.

python print_n.py beta1/n0.9/ beta2/n0.9/ beta3/n0.9/

then

the info() function in print_n.py expands
"beta1/n0.9/"
as
"beta1/n0.9/bin_0.h5", "beta1/n0.9/bin_1.h5", etc...

**Comment by katherineding** [comment]
I understand! how does it look now?

**Comment by edwnh** [comment]
great, thanks! i've merged all the commits

**Pull request merged**
